2022-05-12 06:54:57.783 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x7f4662aca310>
    │    └ <sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x7f4571549cd0>
    └ <sqlalchemy.engine.base.Connection object at 0x7f43100419d0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ {'ip': '180.201.163.246', 'username': 'chase', 'password': '25521639930835554377737715235261182433127306597257179845839015249...
    │      │       └ 'UPDATE device SET ip=%(ip)s, username=%(username)s, password=%(password)s, address=%(address)s, port=%(port)s, valid=%(valid...
    │      └ <function Cursor.execute at 0x7f466218bdc0>
    └ <pymysql.cursors.Cursor object at 0x7f4511316220>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             │    │      └ "UPDATE device SET ip='180.201.163.246', username='chase', password='25521639930835554377737715235261182433127306597257179845...
             │    └ <function Cursor._query at 0x7f4662194280>
             └ <pymysql.cursors.Cursor object at 0x7f4511316220>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
    │    │     └ "UPDATE device SET ip='180.201.163.246', username='chase', password='25521639930835554377737715235261182433127306597257179845...
    │    └ <function Connection.query at 0x7f46621a85e0>
    └ <pymysql.connections.Connection object at 0x7f4545d6b670>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    │    │                │    │                             └ False
    │    │                │    └ <function Connection._read_query_result at 0x7f46621a8c10>
    │    │                └ <pymysql.connections.Connection object at 0x7f4545d6b670>
    │    └ 1
    └ <pymysql.connections.Connection object at 0x7f4545d6b670>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
    │      └ <function MySQLResult.read at 0x7f46621a9430>
    └ <pymysql.connections.MySQLResult object at 0x7f45714b5460>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   │    └ None
                   └ <pymysql.connections.MySQLResult object at 0x7f45714b5460>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
    │      └ <function MysqlPacket.raise_for_error at 0x7f466219dee0>
    └ <pymysql.protocol.MysqlPacket object at 0x7f437f019670>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
    │   │                     │    └ <member '_data' of 'MysqlPacket' objects>
    │   │                     └ <pymysql.protocol.MysqlPacket object at 0x7f437f019670>
    │   └ <function raise_mysql_exception at 0x7f46626e0e50>
    └ <module 'pymysql.err' from '/home/chase/.local/lib/python3.8/site-packages/pymysql/err.py'>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
          │          │      └ 'Lock wait timeout exceeded; try restarting transaction'
          │          └ 1205
          └ <class 'pymysql.err.OperationalError'>

pymysql.err.OperationalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-10999, started daemon 139935067666176)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-10999, started daemon 139935067666176)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-10999, started daemon 139935067666176)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-10999, started daemon 139935067666176)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-10999, started daemon 139935067666176)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 374, in update
    row.update(new)
    │   │      └ {'ip': '180.201.163.246', 'username': 'chase', 'password': '25521639930835554377737715235261182433127306597257179845839015249...
    │   └ <function Query.update at 0x7f466290e0d0>
    └ <sqlalchemy.orm.query.Query object at 0x7f4482d63430>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3221, in update
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f42f51fcd90>
             └ <sqlalchemy.orm.query.Query object at 0x7f4482d63430>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             │    │           │          │             └ immutabledict({'synchronize_session': 'evaluate', '_sa_orm_update_options': default_update_options(_matched_objects=[], _reso...
             │    │           │          └ immutabledict({})
             │    │           └ <sqlalchemy.sql.annotation.AnnotatedUpdate object at 0x7f4511316160>
             │    └ <function Connection._execute_20 at 0x7f4662b8c4c0>
             └ <sqlalchemy.engine.base.Connection object at 0x7f43100419d0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           │    │     │             │               └ immutabledict({'synchronize_session': 'evaluate', '_sa_orm_update_options': default_update_options(_matched_objects=[], _reso...
           │    │     │             └ immutabledict({})
           │    │     └ ({},)
           │    └ <sqlalchemy.engine.base.Connection object at 0x7f43100419d0>
           └ <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.annotation.AnnotatedUpdate object at 0x7f4511316160>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
           │          └ <function Connection._execute_clauseelement at 0x7f4662b8c310>
           └ <sqlalchemy.engine.base.Connection object at 0x7f43100419d0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
          │    └ <function Connection._execute_context at 0x7f4662b8c5e0>
          └ <sqlalchemy.engine.base.Connection object at 0x7f43100419d0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
    │    └ <function Connection._handle_dbapi_exception at 0x7f4662b8c790>
    └ <sqlalchemy.engine.base.Connection object at 0x7f43100419d0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
    │    └ <function raise_ at 0x7f466308c820>
    └ <module 'sqlalchemy.util' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/util/__init__.py'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x7f4662aca310>
    │    └ <sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x7f4571549cd0>
    └ <sqlalchemy.engine.base.Connection object at 0x7f43100419d0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ {'ip': '180.201.163.246', 'username': 'chase', 'password': '25521639930835554377737715235261182433127306597257179845839015249...
    │      │       └ 'UPDATE device SET ip=%(ip)s, username=%(username)s, password=%(password)s, address=%(address)s, port=%(port)s, valid=%(valid...
    │      └ <function Cursor.execute at 0x7f466218bdc0>
    └ <pymysql.cursors.Cursor object at 0x7f4511316220>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             │    │      └ "UPDATE device SET ip='180.201.163.246', username='chase', password='25521639930835554377737715235261182433127306597257179845...
             │    └ <function Cursor._query at 0x7f4662194280>
             └ <pymysql.cursors.Cursor object at 0x7f4511316220>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
    │    │     └ "UPDATE device SET ip='180.201.163.246', username='chase', password='25521639930835554377737715235261182433127306597257179845...
    │    └ <function Connection.query at 0x7f46621a85e0>
    └ <pymysql.connections.Connection object at 0x7f4545d6b670>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    │    │                │    │                             └ False
    │    │                │    └ <function Connection._read_query_result at 0x7f46621a8c10>
    │    │                └ <pymysql.connections.Connection object at 0x7f4545d6b670>
    │    └ 1
    └ <pymysql.connections.Connection object at 0x7f4545d6b670>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
    │      └ <function MySQLResult.read at 0x7f46621a9430>
    └ <pymysql.connections.MySQLResult object at 0x7f45714b5460>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   │    └ None
                   └ <pymysql.connections.MySQLResult object at 0x7f45714b5460>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
    │      └ <function MysqlPacket.raise_for_error at 0x7f466219dee0>
    └ <pymysql.protocol.MysqlPacket object at 0x7f437f019670>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
    │   │                     │    └ <member '_data' of 'MysqlPacket' objects>
    │   │                     └ <pymysql.protocol.MysqlPacket object at 0x7f437f019670>
    │   └ <function raise_mysql_exception at 0x7f46626e0e50>
    └ <module 'pymysql.err' from '/home/chase/.local/lib/python3.8/site-packages/pymysql/err.py'>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
          │          │      └ 'Lock wait timeout exceeded; try restarting transaction'
          │          └ 1205
          └ <class 'pymysql.err.OperationalError'>

sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1205, 'Lock wait timeout exceeded; try restarting transaction')
[SQL: UPDATE device SET ip=%(ip)s, username=%(username)s, password=%(password)s, address=%(address)s, port=%(port)s, valid=%(valid)s WHERE device.ip = %(ip_1)s]
[parameters: {'ip': '180.201.163.246', 'username': 'chase', 'password': '25521639930835554377737715235261182433127306597257179845839015249955232457587357523656513764765219501926959809678734586903258848278053107496228902071 ... (10 characters truncated) ... 24477714132686149035257580340502967764060960412993081722107254555266733515330840342667879462284184975296953695635465690491075892633796916891372050736', 'address': '/home/users/CT/pycharmproject/spiders/', 'port': 6800, 'valid': 1, 'ip_1': '180.201.163.246'}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-05-12 06:55:04.711 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11023, started daemon 139935050356480)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11023, started daemon 139935050356480)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11023, started daemon 139935050356480)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11023, started daemon 139935050356480)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11023, started daemon 139935050356480)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f43220de040>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f43220de040>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f44d0eef130>
             └ <sqlalchemy.orm.query.Query object at 0x7f43220de040>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f44d0eef130>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f4267c4b6a0>
           └ <sqlalchemy.orm.session.Session object at 0x7f44d0eef130>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 06:55:52.472 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11038, started daemon 139934639834880)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11038, started daemon 139934639834880)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11038, started daemon 139934639834880)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11038, started daemon 139934639834880)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11038, started daemon 139934639834880)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f4529ae5280>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f4529ae5280>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f42f52cd370>
             └ <sqlalchemy.orm.query.Query object at 0x7f4529ae5280>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f42f52cd370>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f4529ae5430>
           └ <sqlalchemy.orm.session.Session object at 0x7f42f52cd370>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 06:56:16.535 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11042, started daemon 139935967065856)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11042, started daemon 139935967065856)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11042, started daemon 139935967065856)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11042, started daemon 139935967065856)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11042, started daemon 139935967065856)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f4561cf63d0>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f4561cf63d0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f42f74ca8e0>
             └ <sqlalchemy.orm.query.Query object at 0x7f4561cf63d0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f42f74ca8e0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f426589f0d0>
           └ <sqlalchemy.orm.session.Session object at 0x7f42f74ca8e0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 06:57:08.985 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11053, started daemon 139935537428224)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11053, started daemon 139935537428224)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11053, started daemon 139935537428224)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11053, started daemon 139935537428224)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11053, started daemon 139935537428224)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f42c9ca0880>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f42c9ca0880>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f45701e1490>
             └ <sqlalchemy.orm.query.Query object at 0x7f42c9ca0880>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f45701e1490>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f4571576040>
           └ <sqlalchemy.orm.session.Session object at 0x7f45701e1490>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 06:57:26.022 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11058, started daemon 139935018886912)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11058, started daemon 139935018886912)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11058, started daemon 139935018886912)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11058, started daemon 139935018886912)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11058, started daemon 139935018886912)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f437f019910>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f437f019910>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f42b8efcf10>
             └ <sqlalchemy.orm.query.Query object at 0x7f437f019910>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f42b8efcf10>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f437f019340>
           └ <sqlalchemy.orm.session.Session object at 0x7f42b8efcf10>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 06:57:39.848 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11062, started daemon 139935998797568)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11062, started daemon 139935998797568)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11062, started daemon 139935998797568)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11062, started daemon 139935998797568)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11062, started daemon 139935998797568)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f451035f7c0>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f451035f7c0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f451035fb80>
             └ <sqlalchemy.orm.query.Query object at 0x7f451035f7c0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f451035fb80>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f451035fa90>
           └ <sqlalchemy.orm.session.Session object at 0x7f451035fb80>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 06:58:36.265 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11076, started daemon 139935990404864)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11076, started daemon 139935990404864)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11076, started daemon 139935990404864)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11076, started daemon 139935990404864)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11076, started daemon 139935990404864)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f4560794a00>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f4560794a00>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f45607948b0>
             └ <sqlalchemy.orm.query.Query object at 0x7f4560794a00>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f45607948b0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f4560794a90>
           └ <sqlalchemy.orm.session.Session object at 0x7f45607948b0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 06:58:50.790 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11081, started daemon 139934665012992)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11081, started daemon 139934665012992)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11081, started daemon 139934665012992)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11081, started daemon 139934665012992)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11081, started daemon 139934665012992)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f43766cfca0>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f43766cfca0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f43797eeac0>
             └ <sqlalchemy.orm.query.Query object at 0x7f43766cfca0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f43797eeac0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f43766cfb20>
           └ <sqlalchemy.orm.session.Session object at 0x7f43797eeac0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 06:59:08.835 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11085, started daemon 139934195250944)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11085, started daemon 139934195250944)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11085, started daemon 139934195250944)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11085, started daemon 139934195250944)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11085, started daemon 139934195250944)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f434d3f5700>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f434d3f5700>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f4388329880>
             └ <sqlalchemy.orm.query.Query object at 0x7f434d3f5700>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f4388329880>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f45701e1160>
           └ <sqlalchemy.orm.session.Session object at 0x7f4388329880>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 06:59:27.455 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11089, started daemon 139934160893696)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11089, started daemon 139934160893696)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11089, started daemon 139934160893696)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11089, started daemon 139934160893696)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11089, started daemon 139934160893696)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f4388349a60>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f4388349a60>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f43883491f0>
             └ <sqlalchemy.orm.query.Query object at 0x7f4388349a60>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f43883491f0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f4388349f40>
           └ <sqlalchemy.orm.session.Session object at 0x7f43883491f0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 07:00:14.748 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11097, started daemon 139935018886912)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11097, started daemon 139935018886912)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11097, started daemon 139935018886912)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11097, started daemon 139935018886912)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11097, started daemon 139935018886912)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f425694e9d0>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f425694e9d0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f425694ee50>
             └ <sqlalchemy.orm.query.Query object at 0x7f425694e9d0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f425694ee50>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f4342f61b20>
           └ <sqlalchemy.orm.session.Session object at 0x7f425694ee50>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 07:00:27.352 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11102, started daemon 139935956576000)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11102, started daemon 139935956576000)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11102, started daemon 139935956576000)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11102, started daemon 139935956576000)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11102, started daemon 139935956576000)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f43883299d0>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f43883299d0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f4388329a90>
             └ <sqlalchemy.orm.query.Query object at 0x7f43883299d0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f4388329a90>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f4388329850>
           └ <sqlalchemy.orm.session.Session object at 0x7f4388329a90>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 07:01:16.701 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11111, started daemon 139936007190272)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11111, started daemon 139936007190272)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11111, started daemon 139936007190272)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11111, started daemon 139936007190272)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11111, started daemon 139936007190272)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f452a70d490>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f452a70d490>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f4342f613a0>
             └ <sqlalchemy.orm.query.Query object at 0x7f452a70d490>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f4342f613a0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f452a70d340>
           └ <sqlalchemy.orm.session.Session object at 0x7f4342f613a0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 07:01:36.345 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11116, started daemon 139934160893696)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11116, started daemon 139934160893696)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11116, started daemon 139934160893696)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11116, started daemon 139934160893696)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11116, started daemon 139934160893696)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f44b87a7910>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f44b87a7910>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f43883290a0>
             └ <sqlalchemy.orm.query.Query object at 0x7f44b87a7910>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f43883290a0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f45700ec8e0>
           └ <sqlalchemy.orm.session.Session object at 0x7f43883290a0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 07:01:52.068 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11121, started daemon 139935990404864)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11121, started daemon 139935990404864)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11121, started daemon 139935990404864)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11121, started daemon 139935990404864)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11121, started daemon 139935990404864)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f452a70de80>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f452a70de80>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f44b87a7430>
             └ <sqlalchemy.orm.query.Query object at 0x7f452a70de80>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f44b87a7430>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f452a70de50>
           └ <sqlalchemy.orm.session.Session object at 0x7f44b87a7430>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 07:02:46.392 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11130, started daemon 139934630917888)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11130, started daemon 139934630917888)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11130, started daemon 139934630917888)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11130, started daemon 139934630917888)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11130, started daemon 139934630917888)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f45700ecf70>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f45700ecf70>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f43766cf250>
             └ <sqlalchemy.orm.query.Query object at 0x7f45700ecf70>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f43766cf250>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f45700ecd90>
           └ <sqlalchemy.orm.session.Session object at 0x7f43766cf250>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 07:08:26.984 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11140, started daemon 139936229451520)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11140, started daemon 139936229451520)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11140, started daemon 139936229451520)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11140, started daemon 139936229451520)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11140, started daemon 139936229451520)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f4342f61ee0>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f4342f61ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f44b87a7e50>
             └ <sqlalchemy.orm.query.Query object at 0x7f4342f61ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f44b87a7e50>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f4669e3fb80>
           └ <sqlalchemy.orm.session.Session object at 0x7f44b87a7e50>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 07:09:23.060 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11151, started daemon 139935027279616)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11151, started daemon 139935027279616)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11151, started daemon 139935027279616)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11151, started daemon 139935027279616)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11151, started daemon 139935027279616)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f43430898e0>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f43430898e0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f4388349ac0>
             └ <sqlalchemy.orm.query.Query object at 0x7f43430898e0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f4388349ac0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f43430891c0>
           └ <sqlalchemy.orm.session.Session object at 0x7f4388349ac0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 07:10:15.272 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11164, started daemon 139934150665984)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11164, started daemon 139934150665984)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11164, started daemon 139934150665984)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11164, started daemon 139934150665984)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11164, started daemon 139934150665984)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f4388349760>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f4388349760>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f42c9ca0be0>
             └ <sqlalchemy.orm.query.Query object at 0x7f4388349760>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f42c9ca0be0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f4388349490>
           └ <sqlalchemy.orm.session.Session object at 0x7f42c9ca0be0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 07:11:54.397 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11169, started daemon 139935529035520)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11169, started daemon 139935529035520)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11169, started daemon 139935529035520)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11169, started daemon 139935529035520)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11169, started daemon 139935529035520)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 372, in update
    if row.all():
       │   └ <function Query.all at 0x7f466290b430>
       └ <sqlalchemy.orm.query.Query object at 0x7f42f96c64f0>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
           │    └ <function Query._iter at 0x7f466290bb80>
           └ <sqlalchemy.orm.query.Query object at 0x7f42f96c64f0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f43620805b0>
             └ <sqlalchemy.orm.query.Query object at 0x7f42f96c64f0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
           │    │                    └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Session._connection_for_bind at 0x7f46628e4790>
           └ <sqlalchemy.orm.session.Session object at 0x7f43620805b0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
           │    │            └ <function SessionTransaction._connection_for_bind at 0x7f46628e33a0>
           │    └ <sqlalchemy.orm.session.SessionTransaction object at 0x7f42f96c6400>
           └ <sqlalchemy.orm.session.Session object at 0x7f43620805b0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
           │    └ <function Engine.connect at 0x7f4662b91d30>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3166, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           │    │               │                       └ False
           │    │               └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <class 'sqlalchemy.engine.base.Connection'>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         │      └ <function Engine.raw_connection at 0x7f4662b961f0>
         └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           │    │                  │    │    │        └ None
           │    │                  │    │    └ <function Pool.connect at 0x7f4662bbd280>
           │    │                  │    └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │    │                  └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
           │    └ <function Engine._wrap_pool_connect at 0x7f4662b91dc0>
           └ Engine(mysql+pymysql://root:***@180.201.163.246:33061/spider?autocommit=true&charset=utf8)
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect
    return fn()
           └ <bound method Pool.connect of <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 307, in connect
    return _ConnectionFairy._checkout(self)
           │                │         └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
           │                └ <classmethod object at 0x7f4662bba490>
           └ <class 'sqlalchemy.pool.base._ConnectionFairy'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 767, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            │                 │        └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
            │                 └ <classmethod object at 0x7f4662bba430>
            └ <class 'sqlalchemy.pool.base._ConnectionRecord'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 425, in checkout
    rec = pool._do_get()
          │    └ <function QueuePool._do_get at 0x7f4662b52700>
          └ <sqlalchemy.pool.impl.QueuePool object at 0x7f4571549ee0>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 134, in _do_get
    raise exc.TimeoutError(
          │   └ <class 'sqlalchemy.exc.TimeoutError'>
          └ <module 'sqlalchemy.exc' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/exc.py'>

sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/14/3o7r)
2022-05-12 07:11:52.567 | ERROR    | base.db.mysql:update:389 - 【mysql更新数据出错】
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x7f4662aca310>
    │    └ <sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x7f4571549cd0>
    └ <sqlalchemy.engine.base.Connection object at 0x7f4253167490>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ {'ip': '180.201.163.246', 'username': 'chase', 'password': '96611072867798091844372731499679377840701574322148491248843968751...
    │      │       └ 'UPDATE device SET ip=%(ip)s, username=%(username)s, password=%(password)s, address=%(address)s, port=%(port)s, valid=%(valid...
    │      └ <function Cursor.execute at 0x7f466218bdc0>
    └ <pymysql.cursors.Cursor object at 0x7f42f74caf10>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             │    │      └ "UPDATE device SET ip='180.201.163.246', username='chase', password='96611072867798091844372731499679377840701574322148491248...
             │    └ <function Cursor._query at 0x7f4662194280>
             └ <pymysql.cursors.Cursor object at 0x7f42f74caf10>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
    │    │     └ "UPDATE device SET ip='180.201.163.246', username='chase', password='96611072867798091844372731499679377840701574322148491248...
    │    └ <function Connection.query at 0x7f46621a85e0>
    └ <pymysql.connections.Connection object at 0x7f4393f93a60>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    │    │                │    │                             └ False
    │    │                │    └ <function Connection._read_query_result at 0x7f46621a8c10>
    │    │                └ <pymysql.connections.Connection object at 0x7f4393f93a60>
    │    └ 1
    └ <pymysql.connections.Connection object at 0x7f4393f93a60>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
    │      └ <function MySQLResult.read at 0x7f46621a9430>
    └ <pymysql.connections.MySQLResult object at 0x7f457151c130>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   │    └ None
                   └ <pymysql.connections.MySQLResult object at 0x7f457151c130>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
    │      └ <function MysqlPacket.raise_for_error at 0x7f466219dee0>
    └ <pymysql.protocol.MysqlPacket object at 0x7f425694e310>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
    │   │                     │    └ <member '_data' of 'MysqlPacket' objects>
    │   │                     └ <pymysql.protocol.MysqlPacket object at 0x7f425694e310>
    │   └ <function raise_mysql_exception at 0x7f46626e0e50>
    └ <module 'pymysql.err' from '/home/chase/.local/lib/python3.8/site-packages/pymysql/err.py'>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
          │          │      └ 'Lock wait timeout exceeded; try restarting transaction'
          │          └ 1205
          └ <class 'pymysql.err.OperationalError'>

pymysql.err.OperationalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4689341a60>
    └ <Thread(Thread-11146, started daemon 139934160893696)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7f4689341790>
    └ <Thread(Thread-11146, started daemon 139934160893696)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-11146, started daemon 139934160893696)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-11146, started daemon 139934160893696)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7f457182e160>>
    └ <Thread(Thread-11146, started daemon 139934160893696)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 779, in get_request_from_keywords_hot
    self.start_finished_spider_every_interval(project_names)
    │    │                                    └ ['default']
    │    └ <function ProjectManager.start_finished_spider_every_interval at 0x7f4571552160>
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 764, in start_finished_spider_every_interval
    self[name].start_spider()
    │    └ 'default'
    └ <monitor.projectManager.ProjectManager object at 0x7f457182e160>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 352, in start_spider
    self.update_device_valid(device)
    │    │                   └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    └ <function Project.update_device_valid at 0x7f4571551160>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 404, in update_device_valid
    self.database_manager.mysql.update(Device(**device.to_item()))
    │    │                │     │      │        │      └ <function DeviceC.to_item at 0x7f46621ac1f0>
    │    │                │     │      │        └ <monitor.deviceManager.DeviceC object at 0x7f4571558ee0>
    │    │                │     │      └ <class 'base.db.mysql.Device'>
    │    │                │     └ <function Mysql.update at 0x7f46627c94c0>
    │    │                └ <base.db.mysql.Mysql object at 0x7f4571549e80>
    │    └ <base.db.dbSlot.Slot object at 0x7f4571549940>
    └ <monitor.projectManager.Project object at 0x7f4571558880>

> File "/home/users/Scy/yuqing/spider/base/db/mysql.py", line 374, in update
    row.update(new)
    │   │      └ {'ip': '180.201.163.246', 'username': 'chase', 'password': '96611072867798091844372731499679377840701574322148491248843968751...
    │   └ <function Query.update at 0x7f466290e0d0>
    └ <sqlalchemy.orm.query.Query object at 0x7f4252092b50>

  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3221, in update
    result = self.session.execute(
             │    │       └ <function Session.execute at 0x7f46628e4820>
             │    └ <sqlalchemy.orm.session.Session object at 0x7f4571578f40>
             └ <sqlalchemy.orm.query.Query object at 0x7f4252092b50>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             │    │           │          │             └ immutabledict({'synchronize_session': 'evaluate', '_sa_orm_update_options': default_update_options(_matched_objects=[], _reso...
             │    │           │          └ immutabledict({})
             │    │           └ <sqlalchemy.sql.annotation.AnnotatedUpdate object at 0x7f452a70df70>
             │    └ <function Connection._execute_20 at 0x7f4662b8c4c0>
             └ <sqlalchemy.engine.base.Connection object at 0x7f4253167490>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1583, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           │    │     │             │               └ immutabledict({'synchronize_session': 'evaluate', '_sa_orm_update_options': default_update_options(_matched_objects=[], _reso...
           │    │     │             └ immutabledict({})
           │    │     └ ({},)
           │    └ <sqlalchemy.engine.base.Connection object at 0x7f4253167490>
           └ <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.annotation.AnnotatedUpdate object at 0x7f452a70df70>>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
           │          └ <function Connection._execute_clauseelement at 0x7f4662b8c310>
           └ <sqlalchemy.engine.base.Connection object at 0x7f4253167490>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1452, in _execute_clauseelement
    ret = self._execute_context(
          │    └ <function Connection._execute_context at 0x7f4662b8c5e0>
          └ <sqlalchemy.engine.base.Connection object at 0x7f4253167490>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
    │    └ <function Connection._handle_dbapi_exception at 0x7f4662b8c790>
    └ <sqlalchemy.engine.base.Connection object at 0x7f4253167490>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
    util.raise_(
    │    └ <function raise_ at 0x7f466308c820>
    └ <module 'sqlalchemy.util' from '/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/util/__init__.py'>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x7f4662aca310>
    │    └ <sqlalchemy.dialects.mysql.pymysql.MySQLDialect_pymysql object at 0x7f4571549cd0>
    └ <sqlalchemy.engine.base.Connection object at 0x7f4253167490>
  File "/home/chase/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ {'ip': '180.201.163.246', 'username': 'chase', 'password': '96611072867798091844372731499679377840701574322148491248843968751...
    │      │       └ 'UPDATE device SET ip=%(ip)s, username=%(username)s, password=%(password)s, address=%(address)s, port=%(port)s, valid=%(valid...
    │      └ <function Cursor.execute at 0x7f466218bdc0>
    └ <pymysql.cursors.Cursor object at 0x7f42f74caf10>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
             │    │      └ "UPDATE device SET ip='180.201.163.246', username='chase', password='96611072867798091844372731499679377840701574322148491248...
             │    └ <function Cursor._query at 0x7f4662194280>
             └ <pymysql.cursors.Cursor object at 0x7f42f74caf10>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
    │    │     └ "UPDATE device SET ip='180.201.163.246', username='chase', password='96611072867798091844372731499679377840701574322148491248...
    │    └ <function Connection.query at 0x7f46621a85e0>
    └ <pymysql.connections.Connection object at 0x7f4393f93a60>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    │    │                │    │                             └ False
    │    │                │    └ <function Connection._read_query_result at 0x7f46621a8c10>
    │    │                └ <pymysql.connections.Connection object at 0x7f4393f93a60>
    │    └ 1
    └ <pymysql.connections.Connection object at 0x7f4393f93a60>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
    │      └ <function MySQLResult.read at 0x7f46621a9430>
    └ <pymysql.connections.MySQLResult object at 0x7f457151c130>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
                   │    └ None
                   └ <pymysql.connections.MySQLResult object at 0x7f457151c130>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
    │      └ <function MysqlPacket.raise_for_error at 0x7f466219dee0>
    └ <pymysql.protocol.MysqlPacket object at 0x7f425694e310>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
    │   │                     │    └ <member '_data' of 'MysqlPacket' objects>
    │   │                     └ <pymysql.protocol.MysqlPacket object at 0x7f425694e310>
    │   └ <function raise_mysql_exception at 0x7f46626e0e50>
    └ <module 'pymysql.err' from '/home/chase/.local/lib/python3.8/site-packages/pymysql/err.py'>
  File "/home/chase/.local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
          │          │      └ 'Lock wait timeout exceeded; try restarting transaction'
          │          └ 1205
          └ <class 'pymysql.err.OperationalError'>

sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1205, 'Lock wait timeout exceeded; try restarting transaction')
[SQL: UPDATE device SET ip=%(ip)s, username=%(username)s, password=%(password)s, address=%(address)s, port=%(port)s, valid=%(valid)s WHERE device.ip = %(ip_1)s]
[parameters: {'ip': '180.201.163.246', 'username': 'chase', 'password': '96611072867798091844372731499679377840701574322148491248843968751733835445625486113274269788795405909171662602203785336760424094934804671394025629057 ... (10 characters truncated) ... 65966318293288273168954972741302022629790438468120529319740132908566069026772697273114341104506076610646735782535085957771087205129557443494905705233', 'address': '/home/users/CT/pycharmproject/spiders/', 'port': 6800, 'valid': 1, 'ip_1': '180.201.163.246'}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
